github/site-policy

CONTRIBUTING.md
LICENSE.md
README.md

Change repo license to CC0-1.0 and update corresponding documentation in README and CONTRIBUTING.
Fixes #14

Update outbound license to CC0-1.0

---

Policies/github-corporate-terms-of-service.md

Hey everyone! This is a Draft Update to the GitHub Corporate Terms of Service. We would love feedback on this update. Please take a look at our [Contribution Guidelines](CONTRIBUTING.md) for examples of the types of feedback we're looking for and for other feedback recommendations. 
~These changes will not be effective until July 21, 2017.~
NOTE: Apologies for any confusion, these changes will not be effective until August 7, 2017.

DRAFT UPDATE to GitHub Corporate Terms of Service

---

Policies/dmca-takedown-policy.md

Providing clarification of language related to “fork” definition. As
recommended here: https://github.com/github/site-policy/pull/53
/cc @evandrocoan Thanks!

Edits to "fork" definition

---

Policies/github-corporate-terms-of-service.md
Policies/github-marketplace-terms-of-service.md
Policies/github-open-source-applications-terms-and-conditions.md
Policies/github-privacy-statement.md
Policies/github-terms-of-service.md

Minor updates to the following policies:
- Terms of Service
- Corporate Terms of Service
- Marketplace Terms of Service
- Privacy Statement 
- Open Source Applications Terms and Conditions
Changes:
- Changes to the API section include the removal of redundant language (sections H1 and H3), and consolidation of both termination (section M) and limitation of liability (section P) language in their respective sections.
- Addition of language to Section E. Private Repositories, includes notice about potential opt-in features.

Adding updates

---

Policies/github-sensitive-data-removal-policy.md

We just published a new policy and process for requesting the removal of sensitive data: https://help.github.com/articles/github-sensitive-data-removal-policy/

Adding Sensitive Data Removal Policy

---

Policies/github-corporate-terms-of-service.md

This pull request:
- incorporates the new "Accounts" definition through the agreement
- adds "User-Generated Content" and "User Personal Information" to section J(1) and updates two of the requirements in that section

Incorporate Definitions + Section J update

---

Policies/github-terms-of-service.md

This pull request:
- incorporates the new "Accounts" definition through the agreement
- adds "User-Generated Content" and "User Personal Information" to section J(1) and updates two of the requirements in that section

Incorporate Definitions + Section J update - Terms of Service

---

Policies/github-sensitive-data-removal-policy.md

Added details about process and edited for clarity in response to frequently asked questions; added details about disputes

Added details about process and edited for clarity re: frequently asked questions; added details about disputes

---

Policies/github-terms-of-service.md

Incorporating [suggested edit](https://github.com/github/site-policy/pull/126) from @smichel17 🙇‍♀️

Make "Survival" section readable

---

Policies/global-privacy-practices.md

This update to the Global Privacy Practices policy includes a number of changes for compliance purposes and changes in law, including changes to the following sections:
* Privacy Shield Framework
* `removed` U.S.–Swiss Safe Harbor Framework

Update to Global Privacy Practices - Winter 2019

---

Policies/github-terms-of-service.md

This update to the Terms of Service include a number of changes for compliance purposes and clarifications, including changes to the following sections:
* Account Requirements
* Acceptable Use
* Private Repositories
* Additional Terms for GitHub Pages and Learning Lab
* GitHub Learning Lab

Updates to the standard Terms of Service - Winter 2019

---

Policies/github-and-trade-controls.md

These updates add clarification about affected services and add to the FAQs.

GitHub and Trade Controls Update - Summer 2019

---

Policies/github-subprocessors-and-cookies.md

Adding Microsoft to subprocessor list.

Add Microsoft as subprocessor

---

Policies/github-anti-bribery-statement.md
Policies/github-event-terms.md

This PR updates our Anti-Bribery Statement to note our commitment to Microsoft's Anti-Corruption Policy and fixes typos in Events Terms.

Updates to Anti-Bribery Statement and Event Terms

---

Policies/github-corporate-terms-of-service.md
Policies/github-enterprise-server-license-agreement.md
Policies/github-enterprise-subscription-agreement.md
Policies/github-supplemental-terms-for-microsoft-volume-licensing.md

This PR fixes minor typos and formatting issues found after publication of the Fall 2019 updates.

Minor Enterprise Updates Fall 2019

---

Policies/github-enterprise-subscription-agreement.md

Updating Enterprise Subscription Agreement to account for new product features.

Update Enterprise Subscription Agreement

---

Policies/github-supplemental-terms-for-microsoft-volume-licensing.md

Updating the supplemental volume licensing terms to account for new product features

Update Supplemental Volume Licensing Terms

---

Policies/github-corporate-terms-of-service.md
Policies/github-marketplace-terms-of-service.md
Policies/github-sponsors-additional-terms.md
Policies/github-terms-of-service.md
Policies/guidelines-for-legal-requests-of-user-data.md

Fixing links, adding the Sponsors Program terms to this repository, and other minor updates to align these document versions with the live versions.

Minor Updates - Fall 2019

---

Policies/github-sponsors-additional-terms.md

Add "self-dealing" prohibition to "Acceptable Use" for Sponsors

---

Policies/github-and-trade-controls.md

Updated article re: organizational accounts.

Updates to GitHub and Trade Controls

---

Policies/github-community-guidelines.md
Policies/github-sensitive-data-removal-policy.md

This PR updates the link to contact us in our 
- Community Guidelines 
- Sensitive Data Removal Policy

update contact link

---

Policies/github-additional-product-terms.md

adding section on GitHub Advanced Security to our Additional Product Terms

update Additional Product Terms for GitHub Advanced Security

---

Policies/github-privacy-statement.md
Policies/github-username-policy.md

- updates ` What if the username I want is already taken?`in Username Policy
- fixes typo in address in Privacy Statement

update Username Policy + fix typo in Privacy Statement

---

Policies/github-privacy-statement.md

added sentence about Privacy Shield

Privacy Shield update

---

Policies/github-terms-of-service.md

add link to site-policy docs

---

.github/workflows/mirroring.yml

Updating naming of sync branch to automate opening of PRs on push from GitHub Docs

Action fix

---

Policies/github-subprocessors-and-cookies.md
Policies/guidelines-for-legal-requests-of-user-data.md

Automatic sync with changes from GitHub Docs

Update from repo-sync

---

Policies/github-terms-for-additional-products-and-features.md

Description in subject. Also update effective date.

Add Codespaces to Additional Product Terms

---

Policies/github-terms-for-additional-products-and-features.md

updates Actions terms to note application to self-hosted runners
closes #425 h/t @jsoref

Account for self-hosted runners in Actions terms

---

Policies/github-terms-for-additional-products-and-features.md

adding subsections on
- Use for Development and Testing
- Authorized Developer
- Third Party Repository Service Access
- Self-Hosted Runners on GitHub Actions

Update Actions terms to provide more detail on use

---

Policies/github-terms/github-terms-for-additional-products-and-features.md

1. Open a pull request directly in the [GitHub Docs](https://github.com/github/docs) repo.
2. Open [an issue in this site-policy repo](https://github.com/github/site-policy/issues/new) describing your change and link it to your PR.
3. We will then consider your change and get back to you. Thank you!

Prince.Center.exchanger.todo.gas.on.md
