- Policies/github-business-plan-addendum.md
This is a Draft Update to the GitHub Business Plan Addendum. These changes will not be effective until July 21, 2017. This pull request contains only immaterial changes.
This pull request is closed because we're not looking for feedback right now on these terms. Along with the other updates, this pull request will be reopened and merged on ~July 21, 2017~ August 7, 2017 [EDITED].
> DRAFT UPDATE to GitHub Business Plan Addendum

- Policies/github-marketplace-terms-of-service.md
This is a Draft Update to the GitHub Marketplace Terms of Service. These changes will not be effective until July 21, 2017. This pull request contains only immaterial changes.
This pull request is closed because we're not looking for feedback right now on these terms. Along with the other updates, this pull request will be reopened and merged on ~July 21, 2017~ August 7, 2017 [EDITED].
> DRAFT UPDATE to GitHub Marketplace Terms of Service

- README.md
- Changed title to "Site Policy on GitHub" 
- More description of site policy's purpose
- Emphasized need for users to adapt policy for their own purposes
> Updates to README - Spring 2018

- anti-slavery-statement-2018.md
We are adding GitHub's 2018 Statement Against Modern Slavery and Child Labor to our open-sourced policies. We update this statement each year, and submit it to our Board of Directors for approval. So we won't make any changes to this document in this cycle, but we'll consider comments or feedback in our preparation of the 2019 statement.
> Adding GitHub Statement Against Modern Slavery and Child Labor - 2018

- Policies/github-terms-of-service.md
Most of the changes to our terms are clarifications of pre-existing sections. Here are a few sections we'd like to highlight:
* Third Party Applications: We combined the Marketplace section with general requirements for those creating integrations for other users to provide better protections for GitHub users and their data. The Marketplace section is now called "Third Party Applications," since it now applies to more than just GitHub's Marketplace. We've also added a "Third Party Applications" section to the Privacy Statement to discuss our users' privacy expectations in regards to those applications
* Access to Private Repositories: In Section E, we clarified the purposes for which we may be required to access private repository contents, in line with the security obligations of our …
> Updates to the Standard Terms of Service - Spring 2018

- Policies/github-community-forum-code-of-conduct.md
Add our [Community Forum](https://github.community) Code of Conduct to the set of GitHub's open policies.
> Add GitHub Community Forum Code of Conduct - Spring 2018

- Policies/github-corporate-terms-of-service.md
Most of the changes to our terms are clarifications of pre-existing sections. Here are a few sections we'd like to highlight:
* Third Party Applications — we combined the Marketplace section with general requirements for those creating integrations for other users to provide better protections for GitHub users and their data. The Marketplace section is now called "Third Party Applications," since it now applies to more than just GitHub's Marketplace. We've also added a "Third Party Applications" section to the Privacy Statement to discuss our users' privacy expectations in regards to those applications.
* Access to Private Repositories — in Section E, we clarified the purposes for which we may be required to access private repository contents, in line with the security obligations of our …
> Updates to the Corporate Terms of Service - Spring 2018

- Policies/github-privacy-statement.md
- Policies/github-subprocessors-and-cookies.md
Over the last few months, we've gotten a few questions asking about our General Data Protection Regulation (GDPR) compliance. We are proud to announce that we are compliant with the GDPR. Additionally, we have always provided the same level of privacy protection to our users regardless of their residency, location, or citizenship, and that will not change. We provide strong privacy and security protection to _all_ of our users.
For the most part, our changes to the Privacy Statement are only points of clarification. GitHub doesn't ask for more personal data from our users than we need to provide our services to you. Where we offer you the option of giving us more data, we provide you the ability to access and delete the data you have given us. For example, you can always remove your …
> Privacy statement spring 2018

- Policies/github-trademark-policy.md
Adding required declarations to the Trademark Policy, similar to the requirements for a DMCA notice. Some formatting changes show up in the diff, but there are no deletions in this PR, only additions of the declarations mentioned above.
> Update required declarations in Trademark Policy

- Policies/github-privacy-statement.md
Updating the Privacy Statement to reflect that Hannah Poteat is no longer GitHub’s DPO.
> Edit Privacy Statement for DPO

- Policies/github-and-export-controls.md
This update to the GitHub and Export Controls policy includes clarifications of existing policies, including changes to the following sections:
* GitHub.com
* Enterprise Server
> Update to GitHub and Export Controls policy - Winter 2019

- Policies/github-subprocessors-and-cookies.md
This update to the Subprocessors and Cookies policy updates our subprocessor list and our policy with respect to cookie usage on our website, including changes to the following sections:
* GitHub Subprocessors
* Cookies on GitHub
* Tracking on GitHub
> Update to the GitHub Subprocessors and Cookies policy - Winter 2019

- Policies/github-terms-of-service.md
We created a standalone [Acceptable Use Policies](https://github.com/github/site-policy/blob/master/Policies/github-acceptable-use-policies.md) doc so this PR updates the Terms of Service with the link to that doc.
> Adding link to Acceptable Use Policies doc for detail on section C

- Policies/github-terms-of-service.md
Opening this pull request to show changes that are currently live: https://help.github.com/en/github/site-policy/github-terms-of-service. 
This pull request covers two sets of updates, including updates made on October 8, 2019 and today, November 13, 2019.
October 8 Updates included:
- Alphabetization of the definitions
- Addition of section J. Beta Previews
November 13 Updates include:
- Moving certain product terms sections (e.g. GitHub Pages and Learning Lab) to the new [GitHub Additional Product Terms](https://help.github.com/en/github/site-policy/github-additional-product-terms)
- Moving certain usage limitations to the [Acceptable Use Policy](https://help.github.com/en/github/site-policy/github-acceptable-use-policies)
- Adding pricing language to address usage-based billing for …
> Terms of Service Updates - Fall 2019

- Policies/github-corporate-terms-of-service.md
Opening this pull request to show changes that are currently live: https://help.github.com/en/github/site-policy/github-corporate-terms-of-service. 
The updates in this pull request cover:
- Moving certain product terms sections (e.g. GitHub Pages and Learning Lab) to the new [GitHub Additional Product Terms](https://help.github.com/en/github/site-policy/github-additional-product-terms)
- Moving certain usage limitations to the [Acceptable Use Policy](https://help.github.com/en/github/site-policy/github-acceptable-use-policies)
- Adding pricing language to address usage-based billing for Actions and Packages
- Addition of a Feedback section
> Corporate Terms of Services Updates - Fall 2019

- Policies/github-enterprise-subscription-agreement.md
Opening this pull request to show changes that are currently live: https://help.github.com/en/github/site-policy/github-enterprise-subscription-agreement.
The updates in this pull request cover:
- Clarifications in existing sections and copy/link edits 
- Moving certain product terms sections (e.g. GitHub Pages and Learning Lab) to the new [GitHub Additional Product Terms](https://help.github.com/en/github/site-policy/github-additional-product-terms)
- Moving certain usage limitations to the [Acceptable Use Policy](https://help.github.com/en/github/site-policy/github-acceptable-use-policies)
- Adding additional product terms, where necessary
> Enterprise Subscription Agreement Updates - Fall 2019

- Policies/github-enterprise-cloud-addendum.md
Opening this pull request to show changes that are currently live: https://help.github.com/en/github/site-policy/github-enterprise-cloud-addendum.
The updates in this pull request cover:
- Removal of irrelevant reference to scheduled downtime
> Enterprise Cloud Addendum Updates - Fall 2019

- Policies/github-additional-product-terms.md
Opening this pull request to show changes that are currently live: https://help.github.com/en/github/site-policy/github-additional-product-terms.
This new document allows GitHub to consolidate product-specific terms into a single place for easier navigation. 
- Sections moved from the Terms of Service include: Marketplace, Third Party Integrations, Pages, Learning Lab, and Connect
- This document also adds product-specific terms and clarifications for both new and existing products
> Add GitHub Additional Product Terms - Fall 2019

- Policies/github-supplemental-terms-for-microsoft-volume-licensing.md
Opening this pull request to show changes that are currently live: https://help.github.com/en/github/site-policy/github-supplemental-terms-for-microsoft-volume-licensing.
The updates in this pull request cover:
- Clarifications in existing sections and copy edits 
- Moving certain product terms sections (e.g. GitHub Pages and Learning Lab) to the new [GitHub Additional Product Terms](https://help.github.com/en/github/site-policy/github-additional-product-terms)
- Moving certain usage limitations to the [Acceptable Use Policy](https://help.github.com/en/github/site-policy/github-acceptable-use-policies)
- Adding additional product terms, where necessary
> Supplemental Terms for MSFT Volume Licensing Updates - Fall 2019

- Policies/github-acceptable-use-policies.md
Due to an administrative oversight, the "Advertising on GitHub" section was [removed from the Terms of Service](https://github.com/github/site-policy/pull/191/files#diff-684a8be6be7e60792bfbe28f6f170f5eL210) and an updated version was [added to the AUP](https://github.com/github/site-policy/pull/199/files#diff-4989585d4637bd20c72a71b6c75f297eR66), but the existing version was not moved to the current AUP, which is being done through this pull request.
There are no changes to the current "Advertising on GitHub" language this pull request and this is not a change to GitHub's legal terms or policies. This corrects an oversight that occurred while moving the relevant section from one legal document to another.
> Move Advertising Section to AUP

- Policies/github-privacy-statement.md
We update our policies to reflect the evolution of our products, or in response to changing legal requirements, clarification requests, or user feedback. To that end, we’ve proposed updates to our Privacy Statement in this pull request. 
These include changes in preparation for the California Consumer Privacy Act (CCPA), which goes into effect in January. We also reorganized some sections to present the information with an enhanced flow. Other changes reflect our increasing focus on the security of our platform and services. Please see our blog post for [additional details](https://github.blog/2019-11-11-our-tldr-for-californias-new-privacy-law-do-not-sell/).
Updates to the Privacy Statement will go into effect after the 30-day notice and comment period, on December 20, at 5 pm PT.
> Privacy Statement Updates - Fall 2019

- Policies/github-community-guidelines.md
This pull request makes non-substantive language improvements to the "Building a strong community" section of the Community Guidelines. Specifically:
* Changes "assume no malice" to "communicate with empathy"
* Adds a "respect each other" section
* Combines "be clear" and "stay on topic" into a single section for readability
Background: The [GitHub Community Forum Code of Conduct](https://github.community/t5/Welcome/Code-of-Conduct/m-p/65#M37) was originally based on the [GitHub Community Guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines). While adapting the document for use with the Community Forum, we made the language improvements to more accurately communicate the intended policy. This pull request contributes those downstream improvements back to …
> Language improvements to the community guidelines "Building a strong community" section 

- Policies/github-anti-bribery-statement.md
- Policies/github-statement-against-modern-slavery-and-child-labor.md
updating our anti-bribery and anti-slavery statements so that vendors must comply with either Microsoft's Supplier Code of Conduct or GitHub's anti-bribery and anti-slavery statements
> add option for vendors to comply with Microsoft's Supplier CoC or GitHub's statement

- Policies/github-community-guidelines.md
- Policies/github-deceased-user-policy.md
- Policies/github-sensitive-data-removal-policy.md
This PR adds a new file to explain how an authorized individual of a deceased GitHub user can contact us regarding the deceased user account's content.
> Add deceased user policy

- Policies/github-additional-product-terms.md
Replaces references Spectrum's old terms (which redirect to GitHub's) with link directly to GitHub's.
> Migrate Spectrum to GitHub Terms of Service

- Policies/github-acceptable-use-policies.md
The Acceptable Use Policies link to an "API Terms" section of the Corporate Terms of Service policy, which appears to no longer exist. I did not see any obvious alternative section that would be related, so I've opted to remove that link entirely.
> Remove link to nonexistent CToS API Terms

- Policies/github-additional-product-terms.md
Clarifies that the restriction is on activity that places an undue burden on our servers disproportionate to the benefits provided to users
> clarify meaning of serverless computing

- Policies/github-privacy-statement.md
CCPA has already gone live as of Jan 1, 2020, so updating the tense to reflect that.
> Privacy Statement: Update CCPA Tense

- CONTRIBUTING.md
- README.md
updating CONTRIBUTING and README - tl;dr of the changes and reason (quoting what the revised README will say) 👇 
>When _we_ open a pull request, in most cases, we'll leave it open for 24 hours before the changes go into effect. Comments on and review of our pull requests are welcome, just like in any open source project. For material changes to our [Privacy Statement](/github/site-policy/github-privacy-statement) or [Terms of Service](/github/site-policy/github-terms-of-service#q-changes-to-these-terms) (including our Acceptable Use Policies), we'll post the updates 30 days before they go into effect, as stated in those docs. (We had previously applied a 30-day comment period for most docs in this repo but found that we tend to get feedback soon after we post the changes and were …
> update CONTRIBUTING and README to reflect quicker ships

- Policies/github-insights-and-data-protection-for-your-organization.md
The GitHub Insights feature is available only to GitHub Enterprise Server users. Consequently, some of the links in this policy are to articles that are not available when users view the "Free, pro, team" version of docs.github.com. This results in broken links - as reported by an open source contributor: [Fix broken url in docs](https://github.com/github/docs/pull/637).
I think that the best solution is to show this policy article only when users are browsing the help for GitHub Enterprise Server, which will ensure that all the current (and any future) links work correctly.
> Make article available for GitHub Enterprise Server users only

- Policies/github-additional-product-terms.md
This PR moves section on `prohibited uses` from [Pages documentation](https://docs.github.com/en/github/working-with-github-pages/about-github-pages#prohibited-uses) to the [Pages section](https://docs.github.com/en/github/site-policy/github-additional-product-terms#4-pages) of our Additional Product Terms
(There's no change in content - just moving words around.)
We plan to merge this PR on Monday, Feb. 22.
> Move Pages "prohibited uses" from documentation to terms

- Policies/github-additional-product-terms.md
refresh of the additional product terms, including
- rename GitHub Additional Product Terms to GitHub Terms for Additional Products and Features
- put products/features in alphabetical order
- remove products/features with terms/documentation covered elsewhere (Marketplace, Third Party Integrations, GitLFS, Spectrum)
- add npm
> rename additional product terms and alphabetize them

- Policies/dmca-takedown-policy.md
adds link to Developer Defense Fund https://github.blog/2021-07-27-github-developer-rights-fellowship-stanford-law-school/ in DMCA policy
> add link to Developer Defense Fund in DMCA policy

- Policies/github-marketplace-developer-agreement.md
- Policies/guidelines-for-legal-requests-of-user-data.md
Opening this PR to
- elaborate on exigent circumstances that delay notification of legal requests for user data
- remove outdated references to sections of the GitHub Marketplace Developer Agreement
We'll plan to merge these updates in 24 hours.
> Updates, clarifies wording on guidelines-for-legal-requests-of-user-data and marketplace-developer-agreement 

- Policies/github-terms-for-additional-products-and-features.md
Opening this PR to streamline the list of prohibited uses of Pages in our Additional Product Terms. We'll plan to merge this change at 4PM PT on Monday.
> Update Pages terms and documentation to streamline list of prohibited uses

- Policies/github-terms-for-additional-products-and-features.md
Updating Additional Product Terms to change the name of Octoshift to GitHub Enterprise Importer. 
We'll plan to merge these changes at 3PM PT on Monday.
> Update Additional Product Terms for a name change

- Policies/other-site-policies/github-account-recovery-policy.md
1. Open a pull request directly in the [GitHub Docs](https://github.com/github/docs) repo.
- This PR has been opened per internal documentation practices.  See: https://github.com/github/docs-internal/pull/36950
3. Open [an issue in this site-policy repo](https://github.com/github/site-policy/issues/new) describing your change and link it to your PR.
- https://github.com/github/site-policy/issues/759
5. We will then consider your change and get back to you. Thank you!
This policy is being documented to codify and formalize existing practices regarding how GitHub handles account lockout recovery and to make clear that GitHub Support will not unlock accounts if the user has lost access to all approved means of account recovery.  This policy makes clear GitHub's practices, established to …
> Introduce the GitHub Account Recovery Policy

- Policies/acceptable-use-policies/github-misinformation-and-disinformation.md
Hi! 👋🏽  Today we are proposing a new addition to our [Acceptable Use Policies on Misinformation and Disinformation](https://docs.github.com/site-policy/acceptable-use-policies/github-misinformation-and-disinformation) to address the development of synthetic and manipulated media tools for the creation of non-consensual intimate imagery (NCII) and disinformation.
You can review our proposed Acceptable Use Policy addition here. We invite all stakeholders to comment for the 30-day period from now until May 20, and look forward to learning from and engaging with the community on this important topic. 
Read more about this change on the [GitHub Blog](https://github.blog/2024-04-18-a-policy-proposal-on-our-approach-to-deepfake-tools-and-responsible-ai/).
> Add Policy on Synthetic and Manipulated Media Tools
